StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{68440A1FB5E26172}" {
   Id "ACE-Medical-Defibrillation-DeliverShock"
   Target_en_us "Deliver Shock"
   Status PROOFREADING_PENDING
   Modified 1749313709
   Author "Hypoxic"
   LastChanged "Hypoxic"
  }
  CustomStringTableItem "{68440A1FE780317F}" {
   Id "ACE-MedicalDefibrillation_UserAction_ConnectPatient"
   Target_en_us "Connect patient"
   Target_de_de "Verbinde Patient"
   Status DEVELOPMENT_PENDING
   Modified 1749719023
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{684A8C40BA16FF1E}" {
   Id "ACE-MedicalDefibrillation_UserAction_DeliverShock"
   Target_en_us "Deliver shock"
   Target_de_de "Schock auslösen"
   Modified 1749719135
   Author "Kexanone"
   LastChanged "Kexanone"
  }
  CustomStringTableItem "{68440A1F845D38EF}" {
   Id "ACE-MedicalDefibrillation_UserAction_DisconnectPatient"
   Target_en_us "Disconnect patient"
   Target_de_de "Patient trennen"
   Modified 1749719041
   Author "Kexanone"
   LastChanged "Kexanone"
  }
 }
}